# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps_gpio/ps_gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_gpio || ORIG_REF_NAME==ps_gpio}]

# IP: bd/ps_gpio/ip/ps_gpio_processing_system7_0_0/ps_gpio_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_gpio_processing_system7_0_0 || ORIG_REF_NAME==ps_gpio_processing_system7_0_0}]

# XDC: bd/ps_gpio/ip/ps_gpio_processing_system7_0_0/ps_gpio_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_gpio_processing_system7_0_0 || ORIG_REF_NAME==ps_gpio_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ps_gpio/ps_gpio_ooc.xdc
