# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ravishm/gpio_ps/gpio_ps.cache/wt [current_project]
set_property parent.project_path C:/Users/ravishm/gpio_ps/gpio_ps.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
add_files C:/Users/ravishm/gpio_ps/gpio_ps.srcs/sources_1/bd/ps_gpio/ps_gpio.bd
set_property used_in_implementation false [get_files -all c:/Users/ravishm/gpio_ps/gpio_ps.srcs/sources_1/bd/ps_gpio/ip/ps_gpio_processing_system7_0_0/ps_gpio_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ravishm/gpio_ps/gpio_ps.srcs/sources_1/bd/ps_gpio/ps_gpio_ooc.xdc]
set_property is_locked true [get_files C:/Users/ravishm/gpio_ps/gpio_ps.srcs/sources_1/bd/ps_gpio/ps_gpio.bd]

read_verilog -library xil_defaultlib C:/Users/ravishm/gpio_ps/gpio_ps.srcs/sources_1/bd/ps_gpio/hdl/ps_gpio_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file ps_gpio_wrapper.hwdef }
synth_design -top ps_gpio_wrapper -part xc7z010clg400-1
write_checkpoint ps_gpio_wrapper.dcp
catch { report_utilization -file ps_gpio_wrapper_utilization_synth.rpt -pb ps_gpio_wrapper_utilization_synth.pb }
